### ISSUE TITLE
how can I select index after setAdapter(),except next() or previous()? 

### ISSUE THREAD

**Issue by hqucsx** [zzz40500/Android-PullToNextLayout#1]

**Comment by zzz40500** [comment]
no，it can not，but  you can use  setAdapter(PullToNextAdapter pullToNextAdapter,int  currentIndex) Instead of  setAdapter(), Alternatively wait for next version。

**Comment by hqucsx** [comment]
ok,thanks,I wait for the next version.when will the next version completed?

**Comment by zzz40500** [comment]
come soon.
